[Email]
# 邮件服务器地址
smtp_server = mail.qq.com
# 端口号 (STARTTLS通常为587，SSL通常为465, 非SSL为25)
smtp_port = 25
# 发件人邮箱
sender_email = yourmail@mail.com
# 发件人密码或授权码
sender_password = yourmailpassword

[System]
# 使用 . 代表当前目录。
# 这样程序就会在代码所在的同一个文件夹里去寻找 log 和 日期文件夹。
base_dir = .
# . 或 ./ ：代表当前目录（即运行代码所在的那个文件夹）。
# .. 或 ../ ：代表上一级目录（即当前文件夹的父文件夹）

# 每日对账单所在文件夹名称
daily_statements_dir = ./Daily_Statements

[Schedule]
# 每天触发任务的时间点（用英文逗号分隔）
trigger_times = 09:15, 12:00, 14:30, 16:30

[Retry]
# 发送失败后的统一重试等待时间（单位：分钟）
wait_minutes = 5
# 最大重试次数
max_retries = 3